### ISSUE TITLE
找不到雷电模拟器

### ISSUE THREAD

**Issue by luyan29** [EKsumic/PCRArenaTools#1]
我安装的是去广告绿色版，是不是必须安装官方版本哦，能不能自选雷电路径呀

**Comment by EKsumic** [comment]
是的，我安装的是官方版本，你也去下载官方版本应该没问题；跟路径没有关系，随便。

**Comment by luyan29** [comment]
> 是的，我安装的是官方版本，你也去下载官方版本应该没问题；跟路径没有关系，随便。

我安装官方64 专版也不行，建议说明文件里面加一下。我安装普通版本OK了

**Comment by EKsumic** [comment]
64版本肯定不行，因为标题非“雷电模拟器”，我记得是“雷电模拟器 64位”吧，说明文档里面已经提醒过标题一定要是“雷电模拟器”了

**Comment by luyan29** [comment]
我窗口显示的也是雷电模拟器。现在有新的问题，提示的是请打开对手队伍，我明明按照B站视频进去的，也停留在对手队伍界面了，不知道咋解决

**Comment by luyan29** [comment]
![image](https://user-images.githubusercontent.com/50790636/100540439-547eea00-3278-11eb-86e5-2cdfa14a0798.png)

**Comment by EKsumic** [comment]
嗯，今天下午我也遇到了和你同样问题的，他的问题是“双显示器”，据他所说，关掉了另外一个显示器问题就解决了

**Comment by EKsumic** [comment]
不过在这之前，请检查分辨率是否正确

**Comment by luyan29** [comment]
我并没有双显示器。分辨率按照说明设置的，240dpi  1280*720  平板版

**Comment by EKsumic** [comment]
平板？

**Comment by luyan29** [comment]
缩放与布局  100%

**Comment by EKsumic** [comment]
缩放与布局后，计算机也重启过了吗？

**Comment by luyan29** [comment]
我一直是100%  没更改过。 要不我重启一个电脑试试。

**Comment by EKsumic** [comment]
说明文档的免责声明部分列举了可能造成无法识别的原因

**Comment by EKsumic** [comment]
雷电模拟器→软件设置→其他设置→固定窗口大小，请勾选

**Comment by EKsumic** [comment]
另外，请不要同时开多个模拟器

**Comment by luyan29** [comment]
固定窗口大小勾选了，并没有多开模拟器。电脑也重启了，进去还是老问题。还有，说明文档我并没有看到任何内容。

**Comment by EKsumic** [comment]
https://blog.csdn.net/qq_34673086/article/details/110232632

**Comment by luyan29** [comment]
放弃了，也不知道哪里有问题，估计我是个例

**Comment by EKsumic** [comment]
hxd，说实话我也不能解决你的问题，但我只能肯定是显示器设备显示出的像素点不符合预期；我的相似度是要求达到0.98，明显你那个没达到要求

**Comment by luyan29** [comment]
估计是电脑配置太渣了。悲剧呀。不知道这种手机上是否可以实现，比如autojs啥的，应该不会被检测吧。（本人小白，随口瞎说的）

**Comment by EKsumic** [comment]
可以实现，但是肯定会被检测。（这就是第三方软件，没啥好说的）

**Comment by EKsumic** [comment]
> 估计是电脑配置太渣了。悲剧呀。不知道这种手机上是否可以实现，比如autojs啥的，应该不会被检测吧。（本人小白，随口瞎说的）

已更新：https://github.com/EKsumic/PCRArenaTools/releases/tag/v2.0.1

该版本或许修复了你说的问题，

相似度0.98已调整为0.7。

**Comment by luyan29** [comment]
完美了，可以识别到，公主竞技场的能不能也改改？？

**Comment by EKsumic** [comment]
> 完美了，可以识别到，公主竞技场的能不能也改改？？

已更新：https://github.com/EKsumic/PcrdfansAutoQuery/releases/tag/v1.0.1
